version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: meal_rec_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-1234}
      POSTGRES_DB: ${DB_NAME:-DataMyHealthFinal}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  core-service:
    build: .
    container_name: meal_rec_core
    command: uvicorn app.main_core:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DB_HOST: db
    depends_on:
      - db

  chatbot-service:
    build: .
    container_name: meal_rec_chatbot
    command: uvicorn app.main_chatbot:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      DB_HOST: db
    depends_on:
      - db

  search-service:
    build: .
    container_name: meal_rec_search
    command: uvicorn app.main_search:app --host 0.0.0.0 --port 8002 --reload
    volumes:
      - .:/app
    ports:
      - "8002:8002"
    env_file:
      - .env
    environment:
      DB_HOST: db
    depends_on:
      - db

volumes:
  postgres_data:
